swagger: '2.0'
info:
  version: 1.0.0
  title: A Simple Flashcard Server
schemes:
  - http
basePath: /api
paths:
  /deck:
    post:
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - deck
      operationId: loadDeck
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/deck"
      responses:
        201:
          description: Loaded
          schema:
            $ref: "#/definitions/deck"
        default:
          description: error
          schema:
            $ref: "#/definitions/error"
  /hello:
    get:
      produces:
        - application/json
      parameters:
        - name: name
          required: false
          type: string
          in: query
          description: defaults to World if not given
      operationId: getGreeting
      responses:
        200:
          description: returns a greeting

definitions:
  flashcard:
    type: object
    properties:
      front:
        type: string
      back:
        type: string
  deck:
    type: object
    required:
      - url
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      url:
        type: string
        minLength: 1
      flashcards:
        type: array
        items:
          $ref: '#/definitions/flashcard'
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string
