// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Flashcard flashcard
//
// swagger:model flashcard
type Flashcard struct {

	// back
	Back string `json:"back,omitempty"`

	// front
	Front string `json:"front,omitempty"`
}

// Validate validates this flashcard
func (m *Flashcard) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Flashcard) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Flashcard) UnmarshalBinary(b []byte) error {
	var res Flashcard
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
