// Code generated by go-swagger; DO NOT EDIT.

package deck

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/pytorchtw/flashcard-go/genapi/models"
)

// LoadDeckCreatedCode is the HTTP code returned for type LoadDeckCreated
const LoadDeckCreatedCode int = 201

/*LoadDeckCreated Loaded

swagger:response loadDeckCreated
*/
type LoadDeckCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Deck `json:"body,omitempty"`
}

// NewLoadDeckCreated creates LoadDeckCreated with default headers values
func NewLoadDeckCreated() *LoadDeckCreated {

	return &LoadDeckCreated{}
}

// WithPayload adds the payload to the load deck created response
func (o *LoadDeckCreated) WithPayload(payload *models.Deck) *LoadDeckCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the load deck created response
func (o *LoadDeckCreated) SetPayload(payload *models.Deck) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoadDeckCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*LoadDeckDefault error

swagger:response loadDeckDefault
*/
type LoadDeckDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewLoadDeckDefault creates LoadDeckDefault with default headers values
func NewLoadDeckDefault(code int) *LoadDeckDefault {
	if code <= 0 {
		code = 500
	}

	return &LoadDeckDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the load deck default response
func (o *LoadDeckDefault) WithStatusCode(code int) *LoadDeckDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the load deck default response
func (o *LoadDeckDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the load deck default response
func (o *LoadDeckDefault) WithPayload(payload *models.Error) *LoadDeckDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the load deck default response
func (o *LoadDeckDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *LoadDeckDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
