// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "A Simple Flashcard Server",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/deck": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "deck"
        ],
        "operationId": "loadDeck",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/deck"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Loaded",
            "schema": {
              "$ref": "#/definitions/deck"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/hello": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "getGreeting",
        "parameters": [
          {
            "type": "string",
            "description": "defaults to World if not given",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns a greeting"
          }
        }
      }
    }
  },
  "definitions": {
    "deck": {
      "type": "object",
      "required": [
        "url"
      ],
      "properties": {
        "flashcards": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/flashcard"
          }
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "url": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "flashcard": {
      "type": "object",
      "properties": {
        "back": {
          "type": "string"
        },
        "front": {
          "type": "string"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "A Simple Flashcard Server",
    "version": "1.0.0"
  },
  "basePath": "/api",
  "paths": {
    "/deck": {
      "post": {
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "tags": [
          "deck"
        ],
        "operationId": "loadDeck",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "schema": {
              "$ref": "#/definitions/deck"
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Loaded",
            "schema": {
              "$ref": "#/definitions/deck"
            }
          },
          "default": {
            "description": "error",
            "schema": {
              "$ref": "#/definitions/error"
            }
          }
        }
      }
    },
    "/hello": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "getGreeting",
        "parameters": [
          {
            "type": "string",
            "description": "defaults to World if not given",
            "name": "name",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "returns a greeting"
          }
        }
      }
    }
  },
  "definitions": {
    "deck": {
      "type": "object",
      "required": [
        "url"
      ],
      "properties": {
        "flashcards": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/flashcard"
          }
        },
        "id": {
          "type": "integer",
          "format": "int64",
          "readOnly": true
        },
        "url": {
          "type": "string",
          "minLength": 1
        }
      }
    },
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "flashcard": {
      "type": "object",
      "properties": {
        "back": {
          "type": "string"
        },
        "front": {
          "type": "string"
        }
      }
    }
  }
}`))
}
